### PR TITLE
obscuracam 2017!

### PR DESCRIPTION
**Pull request by n8fr8**
A few small error handling fixes, removal of the Google Play Vision FaceDetect (which doesn't work that well it turns out), and an update of the ffmpeg binary

### CODE REVIEW

**Comment by DavidMOliver** [comment]
Wait - you're removing ALL face detection?

**Comment by n8fr8** [comment]
We are using the more reliable local Android open-source FaceDetection, which is built into the OS, vs using it in combination with the closed source Google Play cloud-enhanced face detection, which hasn't proven to be better, and often worse.

**Comment by n8fr8** [comment]
(In the long run, I want to integrate OpenCV face detect libraries opencv.org

**Comment by DavidMOliver** [comment]
ah - apologies - groovy

**Pull request merged**
